version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=cidenet_db
      - POSTGRES_USER=andre_manager
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5443:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql