version: "3"
services:
  postgres:
    image: postgres:13.0
    container_name: 'postgres'
    command: postgres -c 'max_connections=300'
    ports:
    - "5444:5444"
    environment:
      POSTGRES_PASSWORD: "cidenet_tasking"
      POSTGRES_MULTIPLE_DATABASES: "employees"
    networks:
    - webnet
networks:
  webnet: